name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Inject API Key
      run: |
        echo "Before injection:"
        cat script.js | grep -n "NASA_API_KEY"
        if [ -n "${{ secrets.NASA_API_KEY }}" ]; then
          # Replace the entire apiKey line
          sed -i "s/const apiKey = window\.NASA_API_KEY || 'DEMO_KEY';/const apiKey = '${{ secrets.NASA_API_KEY }}';/g" script.js
          echo "API key injected successfully"
          echo "After injection:"
          cat script.js | grep -n "const apiKey"
        else
          echo "No NASA_API_KEY secret found, using DEMO_KEY"
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
